### ISSUE TITLE
[EPIC] Next Steps for NuGet in C# Dev Kit

### ISSUE THREAD

**Issue by JonDouglas** [microsoft/vscode-dotnettools#1137]
This issue tracks additional enhancements that we would like to ship to the NuGet C# Dev Kit Experience.

- [ ] Use NuGet SDK instead of dotnet CLI
- [ ] [MSBuild `PackageReference` Autocompletion](https://devblogs.microsoft.com/visualstudio/experimental-msbuild-editor/)
- [ ] [Package Management User Interface](https://github.com/microsoft/vscode-dotnettools/issues/62#issuecomment-1582471743)
- [ ] Vulnerability Auditing Notifications

Tracking issues to come. This is not a commitment, just a living roadmap of upcoming features/thoughts on the direction.

Please feel free to provide your feedback here on any experience you'd like to see come to C# Dev Kit + NuGet! 👍

**Comment by xantari** [comment]
Can you add this long standing bug fix to the next steps for nuget in C# Dev Kit as well? 

https://github.com/microsoft/vscode-dotnettools/issues/1476
